apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-platform.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "eks-platform.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
